import { TopNav } from "@/components/navigation/top-nav"
import { Footer } from "@/components/home/footer"

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <TopNav />
      <main className="flex-1 container mx-auto px-4 py-12">
        <div className="max-w-4xl mx-auto space-y-6">
          <div>
            <p className="text-sm text-muted-foreground uppercase tracking-wide mb-2">IELTS WriteBetter</p>
            <h1 className="text-4xl font-bold">Terms of Service</h1>
            <p className="text-muted-foreground mt-2">Last updated: January 2025</p>
          </div>

          <p className="text-muted-foreground">
            By using IELTS WriteBetter, you agree to these terms. Our goal is to help you improve IELTS Writing through
            AI-assisted feedback while keeping your data safe and respecting academic integrity.
          </p>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">Using the product</h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Use the app for learning and practice only. Do not submit AI output as original exam work.</li>
              <li>Keep your account secure. You are responsible for activity that happens under your login.</li>
              <li>
                We may limit usage (for example, when AI quota is high) to keep the service stable for everyone.
              </li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">Content and AI responses</h2>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>Prompts and feedback are generated by AI and may not be perfectly accurate. Always review critically.</li>
              <li>You retain ownership of your submissions. You grant us permission to process them to provide feedback.</li>
              <li>We may provide fallback or sample content when AI is unavailable to avoid interruptions.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">Privacy & data</h2>
            <p className="text-muted-foreground">
              We collect only what is needed to operate the app (account info and the essays you choose to analyze).
              Please review our <a className="text-primary underline" href="/privacy">Privacy Policy</a> for details on
              data handling and your choices.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-2xl font-semibold">Contact</h2>
            <p className="text-muted-foreground">
              If you have questions about these terms, email us via the contact links in the app footer.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  )
}
