"use client"

import { useState, useEffect } from "react"
import { useRouter } from "next/navigation"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { FileText, Eye, Sparkles, Loader2 } from "lucide-react"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { toast } from "sonner"

type Prompt = {
  id: string
  type: "Task 1" | "Task 2"
  title: string
  description: string
  tags: string[]
}

const availableTopics = [
  "Technology",
  "Education",
  "Environment",
  "Health",
  "Society",
  "Government",
  "Economy",
  "Culture",
  "Science",
  "Transportation",
]

export function PromptsLibrary() {
  const router = useRouter()
  const [activeTab, setActiveTab] = useState<string>("all")
  const [selectedTopics, setSelectedTopics] = useState<string[]>([])
  const [previewPrompt, setPreviewPrompt] = useState<Prompt | null>(null)
  const [prompts, setPrompts] = useState<Prompt[]>([])
  const [isLoading, setIsLoading] = useState(false)

  // Generate initial prompts on mount
  useEffect(() => {
    generatePrompts()
  }, [])

  const generatePrompts = async () => {
    setIsLoading(true)
    try {
      const response = await fetch("/api/ai/generate-prompts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          taskType: activeTab === "all" ? null : activeTab,
          topics: selectedTopics.length > 0 ? selectedTopics : availableTopics,
          count: 6,
        }),
      })

      if (!response.ok) {
        throw new Error("Failed to generate prompts")
      }

      const data = await response.json()
      setPrompts(data.prompts)
      toast.success("New prompts generated!")
    } catch (error) {
      console.error("Error generating prompts:", error)
      toast.error("Failed to generate prompts. Please try again.")
    } finally {
      setIsLoading(false)
    }
  }

  const filteredPrompts = prompts.filter((prompt) => {
    const matchesType = activeTab === "all" || prompt.type === activeTab
    const matchesTopics =
      selectedTopics.length === 0 || selectedTopics.some((topic) => prompt.tags.includes(topic))
    return matchesType && matchesTopics
  })

  const toggleTopic = (topic: string) => {
    setSelectedTopics((prev) => (prev.includes(topic) ? prev.filter((t) => t !== topic) : [...prev, topic]))
  }

  const handleUsePrompt = (prompt: Prompt) => {
    // Store the prompt in sessionStorage for use in the new task page
    sessionStorage.setItem("selectedPrompt", JSON.stringify(prompt))
    router.push(`/tasks/new`)
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-3xl font-bold mb-2">AI-Generated Practice Prompts</h1>
        <p className="text-muted-foreground">
          Discover unique IELTS writing prompts generated by AI based on your preferences
        </p>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="mb-6">
        <TabsList>
          <TabsTrigger value="all">All Prompts</TabsTrigger>
          <TabsTrigger value="Task 1">Task 1</TabsTrigger>
          <TabsTrigger value="Task 2">Task 2</TabsTrigger>
        </TabsList>
      </Tabs>

      {/* Topic Selection */}
      <Card className="rounded-2xl border-border bg-card mb-6">
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-base">Select Topics</CardTitle>
            <Button onClick={generatePrompts} disabled={isLoading} size="sm" className="gap-2">
              {isLoading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4" />
                  Generate New Prompts
                </>
              )}
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            {availableTopics.map((topic) => (
              <Badge
                key={topic}
                variant={selectedTopics.includes(topic) ? "default" : "outline"}
                className="cursor-pointer"
                onClick={() => toggleTopic(topic)}
              >
                {topic}
              </Badge>
            ))}
          </div>
          <p className="text-sm text-muted-foreground mt-3">
            {selectedTopics.length === 0
              ? "All topics selected by default. Click to filter specific topics."
              : `${selectedTopics.length} topic(s) selected`}
          </p>
        </CardContent>
      </Card>

      {/* Loading State */}
      {isLoading && (
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-primary" />
            <p className="text-muted-foreground">Generating unique prompts for you...</p>
          </div>
        </div>
      )}

      {/* Prompts Grid */}
      {!isLoading && filteredPrompts.length === 0 && (
        <Card className="rounded-2xl border-border bg-card">
          <CardContent className="py-12 text-center">
            <p className="text-muted-foreground mb-4">No prompts match your filters.</p>
            <Button onClick={generatePrompts} className="gap-2">
              <Sparkles className="h-4 w-4" />
              Generate Prompts
            </Button>
          </CardContent>
        </Card>
      )}

      {!isLoading && filteredPrompts.length > 0 && (
        <div className="grid md:grid-cols-2 gap-6">
          {filteredPrompts.map((prompt) => (
            <Card key={prompt.id} className="rounded-2xl border-border bg-card">
              <CardHeader>
                <div className="flex items-start justify-between mb-2">
                  <Badge variant="outline">{prompt.type}</Badge>
                  <FileText className="h-5 w-5 text-muted-foreground" />
                </div>
                <CardTitle className="text-lg">{prompt.title}</CardTitle>
                <CardDescription className="line-clamp-2">{prompt.description}</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="flex flex-wrap gap-2 mb-4">
                  {prompt.tags.map((tag) => (
                    <Badge key={tag} variant="secondary" className="text-xs">
                      {tag}
                    </Badge>
                  ))}
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setPreviewPrompt(prompt)}
                    className="flex-1 bg-transparent"
                  >
                    <Eye className="mr-2 h-4 w-4" />
                    Preview
                  </Button>
                  <Button size="sm" onClick={() => handleUsePrompt(prompt)} className="flex-1">
                    Use this prompt
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Preview Dialog */}
      <Dialog open={!!previewPrompt} onOpenChange={() => setPreviewPrompt(null)}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <div className="flex items-center gap-2 mb-2">
              <Badge variant="outline">{previewPrompt?.type}</Badge>
            </div>
            <DialogTitle>{previewPrompt?.title}</DialogTitle>
            <DialogDescription className="text-base leading-relaxed pt-4">
              {previewPrompt?.description}
            </DialogDescription>
          </DialogHeader>
          <div className="flex gap-2 pt-4">
            <Button variant="outline" onClick={() => setPreviewPrompt(null)} className="flex-1 bg-transparent">
              Close
            </Button>
            <Button
              onClick={() => {
                if (previewPrompt) handleUsePrompt(previewPrompt)
              }}
              className="flex-1"
            >
              Use this prompt
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}
